import { Theme, ListText } from "theme.slint";
export component PaintedTagText inherits Rectangle {
    in property <ListText> item;
    in property <bool> selected;
    clip:true;
    if root.item.parts.length == 0: Text {
        text:root.item.text;
        color:root.selected ? Theme.highlight-text : root.item.colour;
        vertical-alignment:center;
        overflow:elide;
    }
    if root.item.parts.length > 0: HorizontalLayout {
        spacing:0px;alignment:start;
        for part[index] in root.item.parts: Rectangle {
            min-width:label.preferred-width + 2px;
            preferred-width:label.preferred-width + 2px;
            horizontal-stretch:index == root.item.parts.length - 1 ? 1 : 0;
            background:root.selected ? (part.fade ? @linear-gradient(90deg,part.previous-colour,part.colour) : part.colour) : transparent;
            label := Text {
                text:part.text;
                width:self.preferred-width;
                color:root.selected ? Theme.panel : (part.fade ? @linear-gradient(90deg,part.previous-colour,part.colour) : part.colour);
                vertical-alignment:center;
            }
        }
    }
}
