#!/usr/bin/env python3
"""Generate hydrus-core's case folding table from Python's `str.casefold`.

The reference compares names case-insensitively with `casefold()` (URL class
names in searches, human text sorting). This writes every character whose
casefold differs from itself, with what it folds to, as a Rust table
(crates/hydrus-core/src/casefold_table.rs), so hydrus-rs folds exactly as
the Python the reference runs on does, whatever Unicode version Rust has.

Usage: python oracle/dump_casefold.py
"""

import os
import sys
import unicodedata

HERE = os.path.dirname( os.path.abspath( __file__ ) )

OUT = os.path.join( HERE, '..', 'crates', 'hydrus-core', 'src', 'casefold_table.rs' )


def rust_char( c ):

    return "'\\u{%x}'" % ord( c )


def rust_str( s ):

    return '"' + ''.join( '\\u{%x}' % ord( c ) for c in s ) + '"'


def main():

    rows = []

    for cp in range( 0x110000 ):

        if 0xD800 <= cp <= 0xDFFF:

            continue


        c = chr( cp )

        folded = c.casefold()

        if folded != c:

            rows.append( ( c, folded ) )



    with open( OUT, 'w' ) as f:

        f.write( '// Generated by oracle/dump_casefold.py from Python {} (Unicode {}); do not edit.\n'.format( sys.version.split()[0], unicodedata.unidata_version ) )
        f.write( '\n' )
        f.write( '/// Every character whose `str.casefold()` differs from itself, sorted.\n' )
        f.write( 'pub(crate) static CASEFOLD: &[(char, &str)] = &[\n' )

        for ( c, folded ) in rows:

            f.write( '    ({}, {}),\n'.format( rust_char( c ), rust_str( folded ) ) )


        f.write( '];\n' )


    print( f'wrote {OUT}: {len( rows )} characters' )


if __name__ == '__main__':

    main()
