[package]
name = "hydrus-gui-ui"
description = "The generated Slint UI for the hydrus-rs desktop client."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
test = false
bench = false
doctest = false

[dependencies]
slint.workspace = true

[build-dependencies]
slint-build.workspace = true

[lints]
workspace = true
